[project]
name = "yolov10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "safetensors>=0.6.2",
    "ultralytics>=8.3.204",
]
